# Generated by Django 4.2.3 on 2023-07-26 06:38

from django.db import migrations, models
import django.db.models.deletion
import polloption.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PollOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_start_time", polloption.fields.MinuteDateTimeField()),
                ("event_end_time", polloption.fields.MinuteDateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="PollOptionResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("responder_name", models.CharField(max_length=255)),
                (
                    "response",
                    models.CharField(
                        choices=[("P", "Prefer"), ("Y", "Yes"), ("N", "No")],
                        max_length=1,
                    ),
                ),
                (
                    "poll_option_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polloption.polloption",
                    ),
                ),
            ],
        ),
    ]
