# Generated by Django 4.2.3 on 2023-07-19 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("poll", "0006_remove_polloptionresponse_poll_option_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PollOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_start_time", models.DateTimeField()),
                ("event_end_time", models.DateTimeField()),
                (
                    "poll_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="poll.poll"
                    ),
                ),
            ],
        ),
    ]
