# Generated by Django 4.2.3 on 2023-07-26 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("polloption", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("poll", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="polloptionresponse",
            name="responder_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="polloption",
            name="poll_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="poll.poll"
            ),
        ),
    ]
