# Generated by Django 4.2.3 on 2023-07-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polloption", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polloption",
            name="event_end_time",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="polloption",
            name="event_start_time",
            field=models.CharField(max_length=255),
        ),
    ]
