# Generated by Django 4.2.3 on 2023-07-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polloption', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polloptionresponse',
            name='responder_nonuser_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
