# Generated by Django 4.2.3 on 2023-07-20 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polloption", "0003_alter_polloption_event_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polloption",
            name="event_end_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 20, 17, 5, 37, 666006)
            ),
            preserve_default=False,
        ),
    ]
