# Generated by Django 4.2.3 on 2023-07-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polloption", "0007_alter_polloption_event_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polloption",
            name="event_end_time",
            field=models.DateTimeField(),
        ),
    ]
