# Generated by Django 4.2.3 on 2023-07-20 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polloption", "0009_alter_polloption_event_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polloption",
            name="event_end_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 20, 23, 36, 42, 354557)
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="polloption",
            name="event_start_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 7, 20, 23, 36, 56, 47514)
            ),
            preserve_default=False,
        ),
    ]
