# Generated by Django 4.2.3 on 2023-07-20 17:09

from django.db import migrations
import polloption.fields


class Migration(migrations.Migration):

    dependencies = [
        ("polloption", "0010_alter_polloption_event_end_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polloption",
            name="event_end_time",
            field=polloption.fields.MinuteDateTimeField(),
        ),
        migrations.AlterField(
            model_name="polloption",
            name="event_start_time",
            field=polloption.fields.MinuteDateTimeField(),
        ),
    ]
