# Generated by Django 4.2.3 on 2023-07-23 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polloption", "0011_alter_polloption_event_end_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PollOptionResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response", models.CharField(max_length=8)),
                (
                    "poll_option_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="polloption.polloption",
                    ),
                ),
                (
                    "responder_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
