# Generated by Django 4.2.3 on 2023-07-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polloption", "0012_polloptionresponse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polloptionresponse",
            name="response",
            field=models.CharField(
                choices=[("P", "Prefer"), ("Y", "Yes"), ("N", "No")], max_length=1
            ),
        ),
    ]
