# Generated by Django 4.2.3 on 2023-07-23 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("polloption", "0014_polloptionresponse_responder_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="polloptionresponse",
            name="responder_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
