# Generated by Django 4.2.3 on 2023-07-26 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="username",),
    ]
