# Generated by Django 4.2.3 on 2023-07-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
