# Generated by Django 4.2.3 on 2023-07-17 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("poll", "0002_alter_poll_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="PollOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_start_time", models.DateTimeField()),
                ("event_end_time", models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name="poll", old_name="content", new_name="description",
        ),
        migrations.RenameField(
            model_name="poll", old_name="owner", new_name="owner_id",
        ),
        migrations.AddField(
            model_name="poll",
            name="event_location",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name="poll",
            name="poll_password_hashed",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name="PollResponderXref",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "poll_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="poll.polloption",
                    ),
                ),
                (
                    "responder_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PollOptionResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response", models.CharField(max_length=8)),
                (
                    "poll_option_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="poll.polloption",
                    ),
                ),
                (
                    "responder_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="polloption",
            name="poll_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="poll.poll"
            ),
        ),
    ]
