# Generated by Django 4.2.3 on 2023-07-29 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_pollresponderxref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollresponderxref',
            name='poll_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poll.poll'),
        ),
    ]
