# Generated by Django 4.2.3 on 2023-07-17 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0003_polloption_rename_content_poll_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="poll",
            old_name="poll_password_hashed",
            new_name="poll_password",
        ),
    ]
