# Generated by Django 4.2.3 on 2023-07-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0004_rename_poll_password_hashed_poll_poll_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poll",
            name="event_location",
            field=models.CharField(blank=True, max_length=65535, null=True),
        ),
        migrations.AlterField(
            model_name="poll",
            name="poll_password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="poll", name="title", field=models.CharField(max_length=255),
        ),
    ]
