# Generated by Django 4.2.3 on 2023-07-19 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0005_alter_poll_event_location_alter_poll_poll_password_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="polloptionresponse", name="poll_option_id",),
        migrations.RemoveField(model_name="polloptionresponse", name="responder_id",),
        migrations.RemoveField(model_name="pollresponderxref", name="poll_id",),
        migrations.RemoveField(model_name="pollresponderxref", name="responder_id",),
        migrations.DeleteModel(name="PollOption",),
        migrations.DeleteModel(name="PollOptionResponse",),
        migrations.DeleteModel(name="PollResponderXref",),
    ]
